# SEO
title: Angel Senra
tagline: ""
description: >-
  Angel Senra's official website
url: https://www.angelsenra.com
logo: https://www.angelsenra.com/assets/img/usersnap-selfie.jpg
locale: en_US
defaults:
  - scope:
      path: ""
    values:
      image: https://www.angelsenra.com/assets/img/usersnap-selfie.jpg

email: me@angelsenra.com
baseurl: "" # the subpath of your site, e.g. /blog
github_username: angelsenra
linkedin_username: angelsenra
social:
  name: Angel Senra
  links:
    - https://github.com/angelsenra
    - https://www.linkedin.com/in/angelsenra
google_site_tag: G-NQYGPDCGRJ
show_excerpts: true

minima:
  date_format: "%-d %b %Y"
disqus:
  shortname: angelsenra

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Minima: custom header links
header_pages:
  - _pages/about-me.md
  - _pages/jobs.md
  - _pages/blog.md

footer_pages:
  - _pages/index.md
  - _pages/about-me.md
  - _pages/jobs.md
  - _pages/blog.md

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - CNAME
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
