version: "3"

services:
  jekyll:
    image: bretfisher/jekyll-serve
    environment:
      - JEKYLL_ENV=${JEKYLL_ENV:-development}
    volumes:
      - .:/site
      - jekyll:/usr/local/bundle
    ports:
      - "4000:4000"

volumes:
  jekyll:
